name: Python CI with SonarCloud

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests with coverage
        run: |
          pytest --cov=app --cov-report=xml

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v1.9
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -X
            -Dsonar.projectKey=yrasslansi_sonarcloud-python-lab
            -Dsonar.organization=rasslansi
            -Dsonar.python.version=3.x
            -Dsonar.coverageReportPaths=coverage.xml
